name: Auto-Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 12.x
        env:
          GITHUB_TOKEN: '61be3ebf9635203db3e7a41a30a826d799f5b190'
        run: |
          cd src
          npm install --silent
          npm run build
          cd dist
          npm link
          cd ..
          npm install -g @angular/cli@next
          ng add angular-cli-ghpages
          ng deploy --no-silent --name="AutoDeploy" --email="ryanmracicot@gmail.com"
