name: Auto-Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/setup-node@v1
        with:
          node-version: 12.12.0
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
        run: |
          npm install
          npm run ng -- deploy --base-href="/Portfolio/" --no-silent
      
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Force Rebuild    
        run: |
          git commit -m 'Force rebuild of deployed site' --allow-empty
          
