name: Auto-Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, compile, and deploy to ng-pages branch
      run: |
        echo "Auto-Deploying Rachel's Portfolio to ng-pages"
        npm ci
        npm i --save angular-cli-ghpages@^0.6.2
        ng deploy --base-href="/Portfolio/" --repo=https://github.com/RachelKobernick/Portfolio.git --name="RyanRacicot" --email=ryanmracicot@gmail.com
      env:
        CI: true
